language: cpp
dist: trusty

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - pip install --user -q conan
  - conan user

script:
  - mkdir build && cd build
  - conan install .. --build
  - cmake ..
  - cmake --build .
  - ./bin/test_hello